import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUp, Plus, Trash2, RotateCcw, FolderOpen } from 'lucide-react'
import type { Engine, TranscodeOptions } from '../../shared/types'
import { parameters, parameterGroups, filterLibrary, optionLabels, internalEncoderParameters, x264InternalKeys, type ParameterDefinition, type ParameterValue, type AvOption, type ComponentCapabilities, type FilterSetting } from '../../shared/parameters'
import { Button, Field, Input, Modal, Select, Busy } from './ui'

function AvControl({definition,value,onChange,label}:{definition:AvOption;value?:string;onChange:(value:string)=>void;label?:string}) {
  const name=label??`${optionLabels[definition.name]??definition.name} · ${definition.name}`
  const choices=definition.choices.length?definition.choices:definition.type==='boolean'?[{value:'true',label:'开启'},{value:'false',label:'关闭'},{value:'auto',label:'自动'}]:[]
  return <Field label={name}><div title={definition.description}>{choices.length?<Select aria-label={name} value={value??''} onChange={e=>onChange(e.target.value)}><option value="">不设置</option>{value&&!choices.some(c=>c.value===value)&&<option value={value}>{value}</option>}{choices.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</Select>:<Input aria-label={name} type={['int','int64','float','double'].includes(definition.type)?'number':'text'} min={definition.min} max={definition.max} step={['int','int64'].includes(definition.type)?1:'any'} value={value??''} placeholder={definition.defaultValue===undefined?'不设置':`默认 ${definition.defaultValue}`} onChange={e=>onChange(e.target.value)}/>}</div></Field>
}
function ComponentFields({kind,name,engine,values,onChange,search=''}:{kind:ComponentCapabilities['kind'];name:string;engine?:Engine;values:Record<string,string>;onChange:(key:string,value:string)=>void;search?:string}) {
  const [caps,setCaps]=useState<ComponentCapabilities>(),[error,setError]=useState('')
  useEffect(()=>{let active=true;setCaps(undefined);setError('');if(!engine||['copy','none'].includes(name))return;void window.muxivra.componentCapabilities(kind,name).then(c=>{if(active)setCaps(c)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[engine?.id,kind,name])
  if(!engine)return <p className="hint">请先配置 FFmpeg 引擎</p>
  if(['copy','none'].includes(name))return <p className="hint">选择编码器后可配置专用参数</p>
  if(error)return <p className="error-text">{error}</p>
  if(!caps)return <Busy text="读取引擎参数…"/>
  const visible=caps.options.filter(p=>`${p.name} ${optionLabels[p.name]??''} ${p.description}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="parameter-grid">{visible.map(p=>{const key=values[p.name]!==undefined?p.name:p.aliases?.find(alias=>values[alias]!==undefined)??p.name;return <AvControl key={p.name} definition={p} value={values[key]} onChange={v=>onChange(key,v)}/>})}{!visible.length&&<p className="hint">无可用参数</p>}</div>
}
function ParameterControl({definition:p,value,onChange,engine}:{definition:ParameterDefinition;value?:ParameterValue;onChange:(value?:ParameterValue)=>void;engine?:Engine}) {
  const choices=p.choices??(p.key==='decoder'?engine?.decoders:undefined)
  return <Field label={p.label} hint={p.hint}><div title={p.flag?`FFmpeg -${p.flag}`:undefined}>{choices?<Select aria-label={p.label} value={String(value??'')} onChange={e=>onChange(e.target.value||undefined)}><option value="">自动 / 不设置</option>{choices.map(v=><option key={v} value={v}>{({accurate:'精确定位',fast:'快速定位',on:'开启',off:'关闭',fit:'保持比例',stretch:'拉伸',keep:'保留',remove:'移除',none:'不保留',copy:'复制',metadata:'仅写元数据',convert:'转换像素并写元数据',forever:'无限循环',once:'单次',auto:'自动',bitrate:'目标码率',manual:'专用参数控制'} as Record<string,string>)[v]??v}</option>)}</Select>:<Input aria-label={p.label} type={p.type==='number'?'number':'text'} value={value===undefined?'':String(value)} min={p.min} max={p.max} step={p.integer?1:'any'} placeholder="不设置" onChange={e=>onChange(e.target.value===''?undefined:p.type==='number'?Number(e.target.value):e.target.value)}/>}</div></Field>
}
function FilterEditor({kind,draft,onChange,engine,search}:{kind:'video'|'audio';draft:TranscodeOptions;onChange:(value:TranscodeOptions)=>void;engine?:Engine;search:string}) {
  const filters=draft.filters??[],shown=filters.filter(f=>filterLibrary.find(d=>d.name===f.name)?.kind===kind)
  const [add,setAdd]=useState('')
  const update=(id:string,patch:Partial<FilterSetting>)=>onChange({...draft,filters:filters.map(f=>f.id===id?{...f,...patch}:f)})
  function move(id:string,direction:number){const items=[...filters],index=items.findIndex(f=>f.id===id),target=filters.indexOf(shown[shown.findIndex(f=>f.id===id)+direction]);if(target<0)return;[items[index],items[target]]=[items[target],items[index]];onChange({...draft,filters:items})}
  return <div className="filter-editor"><div className="toolbar"><Select aria-label={`添加${kind==='video'?'视频':'音频'}滤镜`} value={add} onChange={e=>setAdd(e.target.value)}><option value="">选择滤镜</option>{filterLibrary.filter(d=>d.kind===kind).map(d=><option key={d.name} value={d.name} disabled={!!engine&&!engine.filters.includes(d.name)}>{d.category} · {d.label} ({d.name}){engine&&!engine.filters.includes(d.name)?' · 引擎未包含':''}</option>)}</Select><Button disabled={!add} variant="secondary" onClick={()=>{onChange({...draft,filters:[...filters,{id:crypto.randomUUID(),name:add,enabled:true,options:{}}]});setAdd('')}}><Plus size={16}/>添加</Button></div>
    {shown.map((f,index)=><details className="filter-block" key={f.id} open={index===shown.length-1||!!search}><summary><span>{index+1}. {filterLibrary.find(d=>d.name===f.name)?.label} <code>{f.name}</code>{!f.enabled?' · 已停用':''}</span></summary><div className="toolbar filter-actions"><label className="switch-label"><input type="checkbox" checked={f.enabled} onChange={e=>update(f.id,{enabled:e.target.checked})}/>启用</label><Button variant="ghost" size="icon" aria-label={`上移 ${f.name}`} disabled={index===0} onClick={()=>move(f.id,-1)}><ArrowUp size={16}/></Button><Button variant="ghost" size="icon" aria-label={`下移 ${f.name}`} disabled={index===shown.length-1} onClick={()=>move(f.id,1)}><ArrowDown size={16}/></Button><Button variant="ghost" size="sm" onClick={()=>update(f.id,{options:{}})}><RotateCcw size={14}/>重置参数</Button><Button variant="ghost" size="icon" aria-label={`删除滤镜 ${f.name}`} onClick={()=>onChange({...draft,filters:filters.filter(item=>item.id!==f.id)})}><Trash2 size={16}/></Button></div><ComponentFields kind="filter" name={f.name} engine={engine} values={f.options} search={search} onChange={(key,value)=>{const values={...f.options};if(value)values[key]=value;else delete values[key];update(f.id,{options:values})}}/></details>)}
    {!shown.length&&<p className="hint parameter-empty">未添加滤镜</p>}
  </div>
}
export function AdvancedOptions({value,onChange,onClose,engine}:{value:TranscodeOptions;onChange:(value:TranscodeOptions)=>void;onClose:()=>void;engine?:Engine}) {
  const [draft,setDraft]=useState(()=>structuredClone(value)),[group,setGroup]=useState('output'),[search,setSearch]=useState(''),[scope,setScope]=useState<'video'|'audio'>('video')
  const a=draft.advanced??{},needle=search.toLowerCase().trim()
  const visible=parameters.filter(p=>(needle||p.group===group)&&`${p.label} ${p.key} ${p.flag??''}`.toLowerCase().includes(needle))
  const updateAdvanced=(key:string,value?:ParameterValue)=>{const next={...a};if(value===undefined)delete next[key];else next[key]=value;setDraft({...draft,advanced:next,subtitleFile:key==='burnSubtitle'&&value!==undefined?undefined:draft.subtitleFile})}
  const values=Object.fromEntries((draft.encoderOptions??[]).filter(p=>p.scope===scope).map(p=>[p.name,p.value]))
  const count=(key:string)=>key==='videoFilters'||key==='audioFilters'?(draft.filters??[]).filter(f=>f.enabled&&filterLibrary.find(d=>d.name===f.name)?.kind===(key==='videoFilters'?'video':'audio')).length:key==='private'?(draft.encoderOptions??[]).length+Object.keys(draft.codecParameters??{}).length:parameters.filter(p=>p.group===key&&a[p.key]!==undefined).length+(key==='streams'&&draft.subtitleFile?1:0)
  return <Modal title="详细参数" wide onClose={onClose}><div className="advanced-toolbar"><Input aria-label="搜索参数" placeholder="搜索名称或 FFmpeg 参数" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="ghost" onClick={()=>setDraft({...draft,advanced:undefined,filters:undefined,encoderOptions:undefined,metadata:undefined,subtitleFile:undefined,codecParameters:undefined})}><RotateCcw size={16}/>重置详细参数</Button></div><div className="advanced-layout"><nav className="parameter-nav" aria-label="参数分类">{parameterGroups.map(([key,label])=><button key={key} className={group===key&&!needle?'active':''} onClick={()=>{setGroup(key);setSearch('')}}>{label}{count(key)>0&&<span>{count(key)}</span>}</button>)}</nav><div className="parameter-content">
    {visible.length>0&&<div className="parameter-grid">{visible.map(p=><ParameterControl key={p.key} definition={p} value={a[p.key]} onChange={v=>updateAdvanced(p.key,v)} engine={engine}/>)}</div>}
    {!needle&&group==='encoder'&&<Field label="编码速度预设"><Input value={draft.speed} onChange={e=>setDraft({...draft,speed:e.target.value})} placeholder="例如 medium / p4 / 8"/></Field>}
    {group==='videoFilters'&&<FilterEditor kind="video" draft={draft} onChange={setDraft} engine={engine} search={needle}/>}
    {group==='audioFilters'&&<FilterEditor kind="audio" draft={draft} onChange={setDraft} engine={engine} search={needle}/>}
    {group==='private'&&<><div className="toolbar scope-toolbar"><Select aria-label="专用参数类型" value={scope} onChange={e=>setScope(e.target.value as 'video'|'audio')}><option value="video">视频 · {draft.video}</option><option value="audio">音频 · {draft.audio}</option></Select></div>{scope==='video'&&['libx264','libx265'].includes(draft.video)&&<details className="internal-parameters" open={needle?true:undefined}><summary>{draft.video==='libx264'?'x264':'x265'} 内部质量与编码参数</summary><div className="parameter-grid">{internalEncoderParameters.filter(p=>(draft.video!=='libx264'||x264InternalKeys.has(p.key))&&`${p.label} ${p.key}`.toLowerCase().includes(needle)).map(p=><ParameterControl key={p.key} definition={{...p,label:`${p.label} · ${p.key}`}} value={draft.codecParameters?.[p.key]} onChange={value=>{const next={...draft.codecParameters};if(value===undefined)delete next[p.key];else next[p.key]=String(value);setDraft({...draft,codecParameters:next})}} engine={engine}/>)}</div></details>}<ComponentFields kind={scope==='video'?'videoEncoder':'audioEncoder'} name={scope==='video'?draft.video:draft.audio} engine={engine} values={values} search={needle} onChange={(key,value)=>{const items=(draft.encoderOptions??[]).filter(p=>p.scope!==scope||p.name!==key);if(value)items.push({scope,name:key,value});setDraft({...draft,encoderOptions:items})}}/></>}
    {group==='streams'&&!needle&&<><Field label="烧录外部字幕"><div className="input-action"><Input readOnly value={draft.subtitleFile??''} placeholder="选择 SRT / ASS / SSA"/><Button variant="secondary" size="icon" aria-label="选择烧录字幕" onClick={()=> window.muxivra.selectFiles('subtitle-burn').then(paths=>{if(paths[0]){const advanced={...a};delete advanced.burnSubtitle;setDraft({...draft,advanced,subtitleFile:paths[0]})}})}><FolderOpen size={17}/></Button><Button variant="ghost" size="icon" aria-label="移除烧录字幕" onClick={()=>setDraft({...draft,subtitleFile:undefined})}><Trash2 size={16}/></Button></div></Field><Field label="字幕轨道"><Select value={draft.subtitles} onChange={e=>setDraft({...draft,subtitles:e.target.value as 'copy'|'none'})}><option value="none">不保留</option><option value="copy">保留 / 转换文本字幕</option></Select></Field><div className="card-heading"><h3>写入元数据</h3><Button variant="secondary" size="sm" onClick={()=>setDraft({...draft,metadata:[...(draft.metadata??[]),{key:'title',value:''}]})}><Plus size={16}/>添加</Button></div>{(draft.metadata??[]).map((item,index)=><div className="metadata-row" key={index}><Input aria-label={`元数据键 ${index+1}`} value={item.key} onChange={e=>setDraft({...draft,metadata:draft.metadata!.map((v,i)=>i===index?{...v,key:e.target.value}:v)})}/><Input aria-label={`元数据值 ${index+1}`} value={item.value} onChange={e=>setDraft({...draft,metadata:draft.metadata!.map((v,i)=>i===index?{...v,value:e.target.value}:v)})}/><Button variant="ghost" size="icon" aria-label={`删除元数据 ${index+1}`} onClick={()=>setDraft({...draft,metadata:draft.metadata!.filter((_,i)=>i!==index)})}><Trash2 size={16}/></Button></div>)}</>}
    {needle&&!visible.length&&!['videoFilters','audioFilters','private'].includes(group)&&<p className="hint">未找到参数</p>}
  </div></div><div className="advanced-footer"><Button variant="secondary" onClick={onClose}>取消</Button><Button onClick={()=>{onChange({...draft,maxHeight:a.width||a.height?undefined:draft.maxHeight,presetId:undefined});onClose()}}>应用参数</Button></div></Modal>
}
