import { useState } from 'react'
import { Settings2 } from 'lucide-react'
import type { Engine, Preset, TranscodeOptions } from '../../shared/types'
import { Field, Input, Select, Button } from './ui'
import { AdvancedOptions } from './AdvancedOptions'
import { filterLibrary } from '../../shared/parameters'
const filterKind=(name:string)=>filterLibrary.find(f=>f.name===name)?.kind
const videoNames:Record<string,string>={libx264:'H.264 · 软件',libx265:'H.265 · 软件',libsvtav1:'AV1 · 软件',libaom_av1:'AV1 · AOM',libvpx_vp9:'VP9',h264_nvenc:'H.264 · NVIDIA',hevc_nvenc:'H.265 · NVIDIA',av1_nvenc:'AV1 · NVIDIA',h264_qsv:'H.264 · Intel',hevc_qsv:'H.265 · Intel',h264_amf:'H.264 · AMD',hevc_amf:'H.265 · AMD',png:'PNG',mjpeg:'JPEG',gif:'GIF',libwebp:'WebP'}
const audioNames:Record<string,string>={aac:'AAC',libmp3lame:'MP3',flac:'FLAC',pcm_s16le:'PCM 16 位',pcm_s24le:'PCM 24 位',pcm_s32le:'PCM 32 位',libopus:'Opus',libvorbis:'Vorbis',alac:'ALAC',ac3:'AC-3',eac3:'E-AC-3'}
export function OptionsForm({ value, onChange, presets, engine, compact = false }: { value: TranscodeOptions; onChange: (value: TranscodeOptions) => void; presets: Preset[]; engine?: Engine; compact?: boolean }) {
  const [advanced,setAdvanced]=useState(false)
  const update = (patch: Partial<TranscodeOptions>) => onChange({ ...value, ...patch, presetId: undefined })
  const codecs=(kind:'video'|'audio')=>[...new Set([...(kind==='video'?Object.keys(videoNames):Object.keys(audioNames)),...(engine?.encoders.filter(name=>engine.encoderKinds?.[name]===kind)??[]),kind==='video'?value.video:value.audio])]
  const count=Object.keys(value.advanced??{}).length+(value.filters??[]).filter(f=>f.enabled).length+(value.encoderOptions??[]).length+(value.metadata??[]).length+Object.keys(value.codecParameters??{}).length+(value.subtitleFile?1:0)
  const a=value.advanced??{},rate=String(a.rateControl??'auto')
  return <div className={`options-form ${compact?'compact-options':''}`}>
    <Field label="处理预设"><Select value={value.presetId ?? ''} onChange={e => { const preset = presets.find(p => p.id === e.target.value); if (preset) onChange({ ...structuredClone(preset.options), presetId: preset.id, streamIndices: value.streamIndices }) }}><option value="">自定义参数</option>{presets.map(preset => <option key={preset.id} value={preset.id}>{preset.name}</option>)}</Select></Field>
    <div className="form-grid"><Field label="输出格式"><Select value={value.container} onChange={e => {
      const container=e.target.value as TranscodeOptions['container'],images=['png','jpg','webp','gif'].includes(container),audioOnly=['m4a','mp3','flac','wav','ogg','opus','srt'].includes(container)
      const audio=container==='mp3'?'libmp3lame':container==='flac'?'flac':container==='wav'?'pcm_s16le':container==='opus'?'libopus':container==='ogg'?'libvorbis':container==='srt'||images?'none':container==='webm'?'libopus':value.audio==='none'&&!audioOnly?'aac':value.audio
      const video=images?(({png:'png',jpg:'mjpeg',gif:'gif',webp:'libwebp'} as Record<string,string>)[container]):audioOnly?'none':container==='webm'?'libvpx_vp9':value.video==='none'?'libx264':value.video
      const advanced={...a}
      if(video==='none')for(const key of Object.keys(advanced))if(['width','height','scaleAlgorithm','aspectMode','colorMode','burnSubtitle','subtitleFont','subtitleSize','subtitleOutline','subtitleMargin','subtitleAlignment'].includes(key)||['rateControl','videoBitrate','minrate','maxrate','bufsize','qmin','qmax','qcomp','globalQuality','profile','tune','level','encodeThreads','gpu','gop','bFrames','refs','keyintMin','pixelFormat','colorspace','primaries','transfer','colorRange','frameRate','fpsMode','videoFrames','imageQuality','imageLoop'].includes(key))delete advanced[key]
      if(audio==='none')for(const key of ['audioQuality','sampleRate','channels','sampleFormat','compressionLevel','audioDelay'])delete advanced[key]
      update({container,audio,video,subtitles:container==='srt'?'copy':images||audioOnly?'none':value.subtitles,advanced,filters:value.filters?.filter(f=>filterKind(f.name)==='video'?video!=='none':audio!=='none'),encoderOptions:value.encoderOptions?.filter(p=>p.scope==='video'?video===value.video&&video!=='none':audio===value.audio&&audio!=='none'),codecParameters:video===value.video?value.codecParameters:undefined,subtitleFile:video==='none'?undefined:value.subtitleFile,maxHeight:video==='none'?undefined:value.maxHeight})
    }}>{['mp4','mkv','mov','webm','avi','ts','m4a','mp3','wav','flac','ogg','opus','srt','png','jpg','webp','gif'].map(format => <option key={format} value={format}>{format.toUpperCase()}</option>)}</Select></Field><Field label="输出重名"><Select value={value.conflict} onChange={e => update({ conflict: e.target.value as TranscodeOptions['conflict'] })}><option value="reject">拒绝覆盖</option><option value="number">自动编号</option></Select></Field></div>
    <Field label="视频编码"><Select value={value.video} onChange={e=>update({video:e.target.value,codecParameters:undefined,encoderOptions:value.encoderOptions?.filter(p=>p.scope!=='video')})}><option value="copy">复制视频</option><option value="none">不输出视频</option>{codecs('video').filter(key=>!['none','copy'].includes(key)).map(key=><option key={key} value={key} disabled={!!engine&&!engine.encoders.includes(key)}>{videoNames[key]??key}</option>)}</Select></Field>
    {value.video!=='none'&&value.video!=='copy'&&<><div className="form-grid"><Field label="质量控制"><Select value={rate} onChange={e=>update({advanced:{...a,rateControl:e.target.value}})}><option value="auto">自动</option><option value="crf">CRF</option><option value="cq">CQ</option><option value="qp">QP</option><option value="bitrate">目标码率</option><option value="manual">专用参数</option></Select></Field>{rate==='bitrate'?<Field label="视频码率（kbps）"><Input type="number" min={1} value={String(a.videoBitrate??'')} onChange={e=>update({advanced:{...a,videoBitrate:Number(e.target.value)}})}/></Field>:<Field label="质量值"><Input type="number" min={0} max={63} value={value.quality} disabled={rate==='manual'} onChange={e=>update({quality:Number(e.target.value)})}/></Field>}</div><div className="form-grid"><Field label="最高高度"><Select value={value.maxHeight??''} onChange={e=>{const next={...a};delete next.width;delete next.height;update({maxHeight:e.target.value?Number(e.target.value):undefined,advanced:next})}}><option value="">原始尺寸</option>{[480,720,1080,1440,2160,4320].map(height=><option key={height} value={height}>{height}p</option>)}</Select></Field><Field label="帧率"><Input value={String(a.frameRate??'')} placeholder="原始帧率" onChange={e=>{const next={...a};if(e.target.value)next.frameRate=e.target.value;else delete next.frameRate;update({advanced:next})}}/></Field></div></>}
    <div className="form-grid"><Field label="音频编码"><Select value={value.audio} onChange={e=>update({audio:e.target.value,encoderOptions:value.encoderOptions?.filter(p=>p.scope!=='audio')})}><option value="copy">复制音频</option><option value="none">不输出音频</option>{codecs('audio').filter(key=>!['none','copy'].includes(key)).map(key=><option key={key} value={key} disabled={!!engine&&!engine.encoders.includes(key)}>{audioNames[key]??key}</option>)}</Select></Field><Field label="音频码率（kbps）"><Input type="number" min={8} max={1536} step={1} value={value.audioBitrate} disabled={['copy','none','flac'].includes(value.audio)||value.audio.startsWith('pcm_')||a.audioQuality!==undefined} onChange={e=>update({audioBitrate:Number(e.target.value)})}/></Field></div>
    <Button variant="secondary" className="advanced-button" onClick={()=>setAdvanced(true)}><Settings2 size={17}/>详细参数{count>0&&<span className="tag">{count} 项</span>}</Button>
    {advanced&&<AdvancedOptions value={value} onChange={onChange} onClose={()=>setAdvanced(false)} engine={engine}/>}
  </div>
}
