MBTN_LEFT script-message muxivra-toggle
MBTN_LEFT_DBL script-message muxivra-fullscreen
SPACE script-message muxivra-toggle
LEFT script-message muxivra-seek-left
RIGHT script-message muxivra-seek-right
UP script-message muxivra-volume-up
DOWN script-message muxivra-volume-down
m script-message muxivra-mute
f script-message muxivra-fullscreen
ESC script-message muxivra-exit-fullscreen
s script-message muxivra-screenshot
. script-message muxivra-frame-next
, script-message muxivra-frame-previous
[ script-message muxivra-set-start
] script-message muxivra-set-end
Ctrl+z script-message muxivra-undo
Ctrl+Z script-message muxivra-redo
