import { useState } from 'react'
import { Copy, Download, Upload, Plus, Pencil, Trash2 } from 'lucide-react'
import type { Preset, Snapshot } from '../../shared/types'
import { defaultOptions } from '../../core/presets'
import { Button, Card, Field, Input, Modal } from '../components/ui'
import { OptionsForm } from '../components/OptionsForm'
import type { RunAction } from '../components/Jobs'

export function Presets({snapshot,run,busy}:{snapshot:Snapshot;run:RunAction;busy:boolean}) {
  const [editing,setEditing]=useState<Preset>(),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState('')
  const clone=(preset:Preset)=>setEditing({...structuredClone(preset),id:`custom-${crypto.randomUUID()}`,name: `${preset.name} 副本`.slice(0,80)})
  const visible=snapshot.presets.filter(p=>`${p.name} ${p.options.video} ${p.options.audio}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="presets-page"><Card title="预设" aside={<div className="toolbar"><Button variant="secondary" disabled={busy} onClick={()=> run(async()=>{const result=await window.muxivra.importPresets();return result},'预设已导入')}><Upload size={16}/>导入</Button><Button variant="secondary" disabled={busy||!selected.length} onClick={()=> run(()=>window.muxivra.exportPresets(selected),'预设已导出')}><Download size={16}/>导出所选 ({selected.length})</Button><Button disabled={busy} onClick={()=>setEditing({id:`custom-${crypto.randomUUID()}`,name:'新预设',description:'',options:structuredClone(defaultOptions)})}><Plus size={16}/>新建</Button></div>}>
    <div className="preset-search"><Input aria-label="搜索预设" placeholder="搜索预设" value={search} onChange={e=>setSearch(e.target.value)}/><label className="switch-label"><input type="checkbox" aria-label="全选预设" checked={visible.length>0&&visible.every(p=>selected.includes(p.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(p=>p.id)])]:selected.filter(id=>!visible.some(p=>p.id===id)))}/>全选</label></div>
    <div className="preset-table">{visible.map(p=>{const builtIn=!p.id.startsWith('custom-');return <div className="preset-entry" key={p.id}><input type="checkbox" aria-label={`选择预设 ${p.name}`} checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/><div className="preset-description"><strong>{p.name}{builtIn&&<span className="tag">内置</span>}</strong><p>{p.options.container.toUpperCase()} · {p.options.video} · {p.options.audio}</p>{p.description&&<p className="hint">{p.description}</p>}</div><div className="toolbar"><Button variant="ghost" size="sm" disabled={busy} onClick={()=>clone(p)}><Copy size={15}/>复制</Button>{!builtIn&&<><Button variant="ghost" size="sm" disabled={busy} onClick={()=>setEditing(structuredClone(p))}><Pencil size={15}/>编辑</Button><Button variant="ghost" size="icon" aria-label={`删除预设 ${p.name}`} disabled={busy} onClick={()=> run(async()=>{if(confirm(`删除预设“${p.name}”？`)){await window.muxivra.deletePreset(p.id);setSelected(selected.filter(id=>id!==p.id));return true}},'预设已删除')}><Trash2 size={16}/></Button></>}</div></div>})}</div>{!visible.length&&<p className="hint parameter-empty">无匹配预设</p>}
    </Card>{editing&&<Modal title="编辑预设" onClose={()=>setEditing(undefined)}><div className="form-grid"><Field label="预设名称"><Input maxLength={80} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="备注"><Input maxLength={500} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></Field></div><OptionsForm value={editing.options} onChange={options=>setEditing({...editing,options})} presets={snapshot.presets} engine={snapshot.engine}/><div className="advanced-footer"><Button variant="secondary" onClick={()=>setEditing(undefined)}>取消</Button><Button disabled={busy||!editing.name.trim()} onClick={()=> run(async()=>{await window.muxivra.savePreset({...editing,name:editing.name.trim(),options:{...editing.options,streamIndices:undefined,presetId:undefined}});setEditing(undefined);return true},'预设已保存')}>保存预设</Button></div></Modal>}
  </div>
}
