import { useState, useEffect, useRef } from 'react'
import { Trash2, ChevronLeft, ChevronRight } from 'lucide-react'
import type { Snapshot } from '../../shared/types'
import { Card, Select, Input, Button, Modal } from '../components/ui'
import { Jobs, type RunAction } from '../components/Jobs'
import { nameOf } from '../lib/utils'
import { HardwareMonitor } from '../components/HardwareMonitor'
import { TaskDetails } from './TaskDetails'
const pageSize=50
const ended=(status:string)=>!['queued','running','paused'].includes(status)
export function Tasks({snapshot,run,busy,visible}:{snapshot:Snapshot;run:RunAction;busy:boolean;visible:boolean}) {
  const [jobs,setJobs]=useState(snapshot.jobs),[filter,setFilter]=useState('all'),[source,setSource]=useState('all'),[order,setOrder]=useState('queue'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[jump,setJump]=useState('1'),[selected,setSelected]=useState(new Set<string>()),[detail,setDetail]=useState<string>(),[deleting,setDeleting]=useState<string[]>(),[removing,setRemoving]=useState(false)
  const scroll=useRef(0)
  useEffect(()=>setJobs(snapshot.jobs),[snapshot.jobs])
  useEffect(()=>{if(!visible)return;let live=true,pending=false;const timer=setInterval(()=>{if(pending)return;pending=true;void window.muxivra.snapshot().then(s=>{if(live)setJobs(s.jobs)}).catch(()=>{}).finally(()=>{pending=false})},1000);return()=>{live=false;clearInterval(timer)}},[visible])
  useEffect(()=>{setPage(1);setJump('1')},[filter,source,order,search])
  useEffect(()=>{setSelected(old=>{const next=new Set([...old].filter(id=>jobs.some(j=>j.id===id&&ended(j.status))));return next.size===old.size?old:next})},[jobs])
  const counts=[['处理中',jobs.filter(j=>j.status==='running').length],['等待中',jobs.filter(j=>j.status==='queued').length],['已暂停',jobs.filter(j=>j.status==='paused').length],['已完成',jobs.filter(j=>j.status==='completed').length],['失败 / 中断',jobs.filter(j=>['failed','interrupted'].includes(j.status)).length]]
  const shown=jobs.filter(j=>(source==='all'||j.source===source)&&(filter==='all'||filter==='active'&&['queued','running','paused'].includes(j.status)||filter==='failed'&&['failed','interrupted'].includes(j.status)||j.status===filter)&&`${j.plan.input.name} ${nameOf(j.plan.outputPath)}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
  const positions=new Map(jobs.map((j,i)=>[j.id,i]))
  shown.sort((a,b)=>order==='newest'?b.createdAt.localeCompare(a.createdAt):order==='oldest'?a.createdAt.localeCompare(b.createdAt):order==='name'?nameOf(a.plan.outputPath).localeCompare(nameOf(b.plan.outputPath),'zh-CN'):((a.status==='running'||a.pausedFrom==='running'?0:['queued','paused'].includes(a.status)?1:2)-(b.status==='running'||b.pausedFrom==='running'?0:['queued','paused'].includes(b.status)?1:2))||(['queued','paused','running'].includes(a.status)?positions.get(a.id)!-positions.get(b.id)!:b.createdAt.localeCompare(a.createdAt)))
  const totalPages=Math.max(1,Math.ceil(shown.length/pageSize)),current=Math.min(page,totalPages),rows=shown.slice((current-1)*pageSize,current*pageSize),selectable=rows.filter(j=>ended(j.status))
  const select=(id:string,checked:boolean)=>setSelected(old=>{const next=new Set(old);checked?next.add(id):next.delete(id);return next})
  useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages])
  useEffect(()=>setJump(String(current)),[current])
  const changePage=(value:number)=>{setPage(Math.max(1,Math.min(totalPages,value)));window.scrollTo({top:0,behavior:'instant'})}
  const openDetail=(id:string)=>{scroll.current=window.scrollY;setDetail(id);window.scrollTo({top:0,behavior:'instant'})}
  const back=()=>{setDetail(undefined);requestAnimationFrame(()=>window.scrollTo({top:scroll.current,behavior:'instant'}))}
  const remove=async()=>{if(!deleting)return;setRemoving(true);const ids=deleting;try{const result=await run(()=>window.muxivra.deleteJobRecords(ids),'记录已删除');if(result!==undefined){setDeleting(undefined);setSelected(old=>new Set([...old].filter(id=>!ids.includes(id))));if(detail&&ids.includes(detail))back();const fresh=await run(()=>window.muxivra.snapshot());if(fresh)setJobs(fresh.jobs)}}finally{setRemoving(false)}}
  const pagination=(bottom=false)=><div className="task-pagination"><span className="hint">{shown.length?`${(current-1)*pageSize+1}–${Math.min(current*pageSize,shown.length)}`:'0'} / {shown.length} 条 · 每页 50 条</span><div className="toolbar"><Button variant="secondary" size="sm" aria-label={bottom?'底部上一页':'上一页'} disabled={current===1||busy} onClick={()=>changePage(current-1)}><ChevronLeft size={15}/></Button><span className="task-page-number">第 {current} / {totalPages} 页</span><Button variant="secondary" size="sm" aria-label={bottom?'底部下一页':'下一页'} disabled={current===totalPages||busy} onClick={()=>changePage(current+1)}><ChevronRight size={15}/></Button>{!bottom&&<><Input aria-label="跳转页码" type="number" min={1} max={totalPages} value={jump} onChange={e=>setJump(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&Number.isInteger(+jump))changePage(+jump)}}/><Button variant="secondary" size="sm" disabled={busy||!jump||!Number.isInteger(+jump)||+jump<1||+jump>totalPages} onClick={()=>changePage(+jump)}>跳转</Button></>}</div></div>
  return <div className="tasks-layout">{detail?<TaskDetails key={detail} id={detail} visible={visible} run={run} busy={busy} onBack={back} onDelete={setDeleting}/>:<><div className="task-stats">{counts.map(([label,count])=><div key={label}><span>{label}</span><strong>{count}</strong></div>)}</div><Card title="处理队列" aside={<span className="hint" title="已结束记录保留最近 1000 条；未完成任务不自动清理">历史上限 1000 · 并行上限 {snapshot.settings.concurrency}</span>}>
    <div className="task-toolbar"><Input aria-label="搜索任务" placeholder="搜索输入或输出文件名" value={search} onChange={e=>setSearch(e.target.value)}/><Select aria-label="任务状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部状态</option><option value="active">未完成</option><option value="running">处理中</option><option value="queued">等待中</option><option value="paused">已暂停</option><option value="completed">已完成</option><option value="failed">失败 / 中断</option><option value="cancelled">已取消</option></Select><Select aria-label="任务来源" value={source} onChange={e=>setSource(e.target.value)}><option value="all">全部来源</option><option value="gui">界面提交</option><option value="mcp">AI 提交</option></Select><Select aria-label="显示顺序" value={order} onChange={e=>setOrder(e.target.value)}><option value="queue">队列顺序</option><option value="newest">最新提交</option><option value="oldest">最早提交</option><option value="name">文件名</option></Select></div>
    <div className="task-selection-toolbar"><label><input type="checkbox" aria-label="选择本页记录" disabled={!selectable.length||busy} checked={!!selectable.length&&selectable.every(j=>selected.has(j.id))} onChange={e=>setSelected(old=>{const next=new Set(old);selectable.forEach(j=>e.target.checked?next.add(j.id):next.delete(j.id));return next})}/>选择本页</label><Button variant="ghost" size="sm" disabled={busy||!shown.some(j=>ended(j.status))} onClick={()=>setSelected(new Set(shown.filter(j=>ended(j.status)).map(j=>j.id)))}>选择全部匹配记录</Button>{selected.size>0&&<><span className="hint">已选 {selected.size} 条</span><Button variant="ghost" size="sm" onClick={()=>setSelected(new Set())}>取消选择</Button></>}<Button variant="secondary" size="sm" disabled={busy||!selected.size} onClick={()=>setDeleting([...selected])}><Trash2 size={15}/>删除所选</Button></div>
    {pagination()}<Jobs jobs={rows} allJobs={jobs} run={run} busy={busy} reorder={order==='queue'} onDetails={openDetail} onDelete={setDeleting} selected={selected} onSelect={select}/>{pagination(true)}
  </Card></>}<HardwareMonitor visible={visible}/>
  {deleting&&<Modal title="删除任务记录" locked={removing} onClose={()=>setDeleting(undefined)}><p>删除 {deleting.length} 条已结束记录及其日志？输入和输出媒体文件会保留。</p><div className="toolbar"><Button variant="secondary" disabled={removing} onClick={()=>setDeleting(undefined)}>取消</Button><Button disabled={busy&&!removing} loading={removing} loadingText="正在删除…" onClick={remove}><Trash2 size={16}/>删除记录</Button></div></Modal>}
  </div>
}
