import { _electron as electron } from 'playwright'
import electronPath from 'electron'
import { mkdir,mkdtemp,writeFile,readFile,rm } from 'node:fs/promises'
import { join,resolve,relative,isAbsolute,sep } from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import assert from 'node:assert/strict'
import koffi from 'koffi'
const exec=promisify(execFile)
await mkdir('.test-data',{recursive:true});await mkdir('artifacts/qa',{recursive:true})
const root=await mkdtemp(resolve('.test-data','ui-')),output=join(root,'output');await mkdir(output)
const input=join(root,'ui.mp4')
await exec('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=1280x720:rate=24','-t','12','-c:v','libx264','-preset','ultrafast',input],{windowsHide:true})
const desktop=await electron.launch({executablePath:process.env.MUXIVRA_EXECUTABLE||electronPath,args:process.env.MUXIVRA_EXECUTABLE?[]:['.'],cwd:process.cwd(),env:{...process.env,MUXIVRA_SMOKE:'1',MUXIVRA_DATA_PATH:join(root,'profile'),MUXIVRA_ENGINE_PATH:join(root,'engines')},timeout:60000})
let closed=false
try {
  const page=await desktop.firstWindow(),errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.getByRole('heading',{name:'单文件',exact:true}).waitFor({timeout:60000})
  const version=await desktop.evaluate(({app})=>app.getVersion())
  await desktop.evaluate(({dialog},input)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[input]});dialog.showMessageBox=async()=>{throw new Error('退出使用了系统原生提示框')}},input)
  // Controlled latency tests exercise the real IPC handler after the delay.
  const delay=async(method,ms)=>desktop.evaluate(({ipcMain},{method,ms})=>{
    const key=`muxivra:${method}`,original=ipcMain._invokeHandlers.get(key)
    if(!original)throw new Error(`Missing IPC handler ${key}`)
    ipcMain.removeHandler(key);ipcMain.handle(key,async(event,...args)=>{await new Promise(resolve=>setTimeout(resolve,ms));return original(event,...args)})
  },{method,ms})
  const shot=async name=>page.screenshot({path:`artifacts/qa/ui-${name}.png`})
  const waitSnapshot=async predicate=>{for(let i=0;i<200;i++){const snapshot=await page.evaluate(()=>window.muxivra.snapshot());if(predicate(snapshot))return snapshot;await page.waitForTimeout(100)}throw new Error('Snapshot timeout')}
  await delay('inspectPlayback',800)
  await page.getByRole('button',{name:'选择媒体文件',exact:true}).click()
  assert.equal(await page.getByRole('button',{name:'选择媒体文件',exact:true}).getAttribute('aria-busy'),'true')
  assert.equal(await page.locator('.operation-status .spin').count(),1)
  await page.waitForFunction(async()=>{const s=await window.muxivra.playerState('single');return s.ready&&!s.loading&&s.videoWidth===1280})
  await page.waitForFunction(()=>document.querySelector('[data-player-owner="single"] .mpv-viewport:not(.audio-viewport)'))
  await page.waitForTimeout(250)
  const user=koffi.load('user32.dll'),find=user.func('uintptr_t __stdcall FindWindowExW(uintptr_t parent, uintptr_t after, str16 name, str16 title)'),visible=user.func('bool __stdcall IsWindowVisible(uintptr_t window)')
  const main=await desktop.evaluate(({BrowserWindow})=>Number(BrowserWindow.getAllWindows()[0].getNativeWindowHandle().readBigUInt64LE())),surface=Number(find(main,0,'STATIC',null))
  assert.ok(surface);assert.equal(visible(surface),true)
  await page.getByRole('combobox',{name:'视频编码',exact:true}).click()
  const viewport=page.locator('.select-viewport');await viewport.waitFor()
  assert.equal(await page.locator('.select-scroll').count(),0)
  const metrics=await viewport.evaluate(e=>({height:e.clientHeight,total:e.scrollHeight}))
  assert.ok(metrics.total>metrics.height);await page.getByRole('scrollbar',{name:'选项滚动'}).waitFor();assert.ok((await page.locator('.select-scroll-thumb').boundingBox()).height>=27)
  const box=await viewport.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.wheel(0,260)
  await page.waitForFunction(()=>document.querySelector('.select-viewport').scrollTop>100)
  await viewport.evaluate(e=>{e.scrollTop=0});await page.waitForTimeout(100)
  const track=await page.getByRole('scrollbar',{name:'选项滚动'}).boundingBox()
  await page.mouse.move(track.x+track.width/2,track.y+12);await page.mouse.down();await page.mouse.move(track.x+track.width/2,track.y+160,{steps:12});await page.mouse.up()
  await page.waitForFunction(()=>document.querySelector('.select-viewport').scrollTop>100)
  await page.waitForTimeout(200);assert.equal(await page.getByRole('listbox').isVisible(),true,'拖动滑条后菜单意外关闭');assert.equal(visible(surface),true);await shot('dropdown-scrollbar');await page.keyboard.press('Escape')
  // Keyboard traversal still scrolls the selected option into view.
  await page.getByRole('combobox',{name:'视频编码',exact:true}).click();await page.keyboard.press('End');await page.keyboard.press('Enter')
  await page.getByRole('combobox',{name:'视频编码',exact:true}).click();await page.getByRole('option',{name:'H.264 · 软件',exact:true}).click()
  await page.getByRole('heading',{name:'单文件',exact:true}).dblclick();assert.equal(await page.evaluate(()=>getSelection()?.toString()),'')
  const editable=page.getByLabel('输出文件名',{exact:true});await editable.fill('selection.mp4');await editable.press('Control+A');assert.equal(await editable.evaluate(e=>e.selectionEnd-e.selectionStart),13)
  await page.evaluate(()=>window.muxivra.requestExit());await page.getByRole('dialog',{name:'退出 Muxivra',exact:true}).waitFor();await page.waitForTimeout(100);assert.equal(visible(surface),false)
  await page.getByRole('button',{name:'继续运行',exact:true}).click();await page.getByRole('dialog',{name:'退出 Muxivra',exact:true}).waitFor({state:'hidden'});await page.waitForTimeout(100);assert.equal(visible(surface),true)
  await page.getByRole('button',{name:'设置',exact:true}).click()
  assert.equal(await page.locator('.hardware-summary-item').count(),3)
  assert.ok(await page.locator('.hardware-summary-item').evaluateAll(items=>items.every(e=>getComputedStyle(e).borderTopStyle==='solid'&&parseFloat(getComputedStyle(e).borderTopWidth)>=.5)))
  await shot('settings-dark')
  await delay('saveSettings',800)
  await page.getByRole('combobox',{name:'界面主题',exact:true}).click();await page.getByRole('option',{name:'浅色',exact:true}).click();await page.getByRole('button',{name:'保存设置',exact:true}).click()
  assert.equal(await page.getByRole('button',{name:'保存设置',exact:true}).getAttribute('aria-busy'),'true')
  await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await shot('settings-light')
  await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({width:1040,height:720}));await shot('settings-minimum')
  assert.ok((await page.locator('.hardware-summary').boundingBox()).height<300)
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
  await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({width:1380,height:910}))
  await desktop.evaluate(({dialog},output)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[output]})},output);await page.evaluate(()=>window.muxivra.selectDirectory('output'))
  const jobs=await page.evaluate(async({input,output})=>{const snapshot=await window.muxivra.snapshot(),options=snapshot.presets.find(p=>p.id==='h264-1080').options;return window.muxivra.submit(['running.mp4','queued.mp4','retained.mp4'].map((name,i)=>({inputPath:input,outputPath:output+'\\'+name,options:i===0?{...options,video:'libx265',audio:'none',speed:'veryslow',advanced:{encodeThreads:1}}:options})))},{input,output})
  await waitSnapshot(s=>s.jobs.find(j=>j.id===jobs[0].id)?.processedMs>0)
  await page.locator('.navigation').getByRole('button',{name:/^任务/}).click()
  const row=id=>page.locator(`.job[data-job-id="${id}"]`)
  assert.equal(await row(jobs[0].id).evaluate(e=>getComputedStyle(e).borderTopStyle),'solid')
  await row(jobs[2].id).getByRole('button',{name:'暂停',exact:true}).click();await row(jobs[2].id).getByText('已暂停',{exact:true}).waitFor()
  await delay('cancel',900);await row(jobs[1].id).getByRole('button',{name:'取消',exact:true}).click()
  const cancelButton=row(jobs[1].id).getByRole('button',{name:'取消中…',exact:true});await cancelButton.waitFor()
  assert.equal(await cancelButton.getAttribute('aria-busy'),'true');assert.equal(await cancelButton.isDisabled(),true);assert.equal(await row(jobs[1].id).locator('.button-spinner').count(),1);await shot('cancel-feedback')
  await row(jobs[1].id).getByText('已取消',{exact:true}).waitFor();assert.equal(await row(jobs[1].id).getAttribute('aria-busy'),null)
  await row(jobs[0].id).getByRole('button',{name:'暂停',exact:true}).click();await row(jobs[0].id).getByText('已暂停',{exact:true}).waitFor()
  await row(jobs[0].id).getByRole('button',{name:'取消',exact:true}).click();await cancelButton.waitFor({state:'hidden'})
  await row(jobs[0].id).getByText('已取消',{exact:true}).waitFor();await shot('tasks-light')
  await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());assert.equal(await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),false)
  await page.evaluate(()=>window.muxivra.requestExit());await page.getByRole('dialog',{name:'退出 Muxivra',exact:true}).waitFor();assert.equal(await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),true)
  await shot('exit-light');await page.getByRole('button',{name:'继续运行',exact:true}).click();await page.getByRole('dialog',{name:'退出 Muxivra',exact:true}).waitFor({state:'hidden'})
  assert.equal(await page.evaluate(()=>window.muxivra.exitState()),undefined)
  await page.evaluate(()=>window.muxivra.requestExit());await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'退出 Muxivra',exact:true}).waitFor({state:'hidden'})
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.evaluate(()=>window.muxivra.requestExit());await shot('exit-dark')
  await delay('respondToExit',1000)
  const exited=desktop.waitForEvent('close');await page.getByRole('button',{name:'退出应用',exact:true}).click()
  await page.getByRole('status').filter({hasText:'正在关闭应用…'}).waitFor();assert.equal(await page.getByRole('dialog',{name:'退出 Muxivra',exact:true}).getByRole('button',{name:'关闭',exact:true}).isDisabled(),true)
  await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog',{name:'退出 Muxivra',exact:true}).isVisible(),true);await shot('exit-closing')
  await exited;closed=true
  const persisted=JSON.parse(await readFile(join(root,'profile','jobs.json'),'utf8'));assert.equal(persisted.find(j=>j.id===jobs[2].id).status,'paused')
  assert.deepEqual(errors,[])
  const report={appVersion:version,executable:process.env.MUXIVRA_EXECUTABLE||'development',dropdownWheelAndThumbDrag:true,dropdownKeyboard:true,noScrollArrows:true,ordinaryTextNotSelectable:true,inputsEditable:true,nestedHardwareAndTaskCards:true,delayedImportSaveCancelFeedback:true,cancelWaitsForFinalStatus:true,trayCustomExit:true,exitCancelAndEscape:true,exitClosingFeedbackAndLock:true,noNativeExitDialog:true,themes:['dark','light'],minimumWindow:[1040,720],errors}
  await writeFile('artifacts/qa/ui-smoke.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))
} finally {
  if(!closed)await desktop.close();const rel=relative(resolve('.test-data'),root);if(rel&&!rel.startsWith(`..${sep}`)&&!isAbsolute(rel))await rm(root,{recursive:true,force:true})
}
